### ISSUE TITLE
Timeline semaphore layer forces VK_KHR_timeline_semaphore extension

### ISSUE THREAD

**Issue by djdeath** [KhronosGroup/Vulkan-ExtensionLayer#1] opened 2020-01-15 16:47 UTC
In order to allow this layer to pass CTS together with an implementation not supporting the timeline semaphore extension, I had to override the implementation's returned list of supported extension : https://github.com/KhronosGroup/Vulkan-ExtensionLayer/blob/master/layers/timeline_semaphore.c#L1948

This is probably wrong but it works and there are currently no other way of achieving that goal.

**Comment by sfricke-samsung** [comment] 2020-08-25 16:22
So the layers and loaders are allowed to expose extensions on-top of the implementation, look at `VK_EXT_validation_features`

I think this is intended behavior as an app could have a 

```
if ("VK_KHR_timeline_semaphore" not supported) {
     setFallbackPath() // or warn that app isn't supported
}
```

So I personally don't see this as an issue

**Comment by djdeath** [comment] 2020-08-25 16:31
Not sure how to read your comment, are you saying we shouldn't force the layer or the opposite?

If we shouldn't force it, then there needs to be a feature in the CTS to add a particular extension for a run.

**Comment by sfricke-samsung** [comment] 2020-08-25 16:33
sorry for very ambiguous comment... I fully support exposing it

**Comment by juan-lunarg** [comment] 2023-04-18 19:17
Discussed internally. Due to lack of interest/activity marking as wontfix.

**Closed by juan-lunarg** 2023-04-18 19:17 UTC
Labels: wontfix
